sudo: false
cache: pip

addons:
  postgresql: "9.2" # minimal postgresql version for the daterange method
  apt:
   packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow


language: python

python:
  - "2.7"

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: MZ5W99aYtT5mntw9Aur7bZ0FFXHZYc3v2oWg9dEODeKcLWUTmQbPC/T/pcjex1MBQTIHy0GZ+M/kj7qQQilbtbMYnjt7VBcY+fY1cZskEohc7mK/c8sUNHeUYj7Ec7n7VriY0XjQVH7Ov3FkiDoUm/4um0VyhH8LpKWw0vMhqFY=
  
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

before_install:
  - "export DISPLAY=:910.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - export WKHTMLTOPDF_VERSION=0.12.4
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
