addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/reporting-engine ${HOME}/reporting-engine -b ${VERSION}
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - sudo wget http://downloads.sourceforge.net/project/wkhtmltopdf/archive/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb -P /tmp/
  - sudo dpkg -i /tmp/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
